### PR TITLE
Update openAPI spec

### PR DESCRIPTION
**Pull request by Magnus-Kuhn**
# Readiness checklist

-   [ ] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

### CODE REVIEW

**Review by jkoenig134 — APPROVED** [review]
LGTM

**Review by jkoenig134 — APPROVED** [review]
LGTM again :)

**Comment by jkoenig134** [comment]
@Magnus-Kuhn if you are waiting for more reviews here please inform the people you are waiting for that this is eager.

**Comment by Magnus-Kuhn** [comment]
> @Magnus-Kuhn if you are waiting for more reviews here please inform the people you are waiting for that this is eager.

If you're happy with the current reviews, I'm happy :)

**Pull request merged**
