### PR TITLE
Re-add deprecated function deleteThirdPartyOwnedRelationshipAttributeAndNotifyPeer

### PR DESCRIPTION
**Pull request by Milena-Czierlinski**
For backwards compatibility

# Readiness checklist

-   [ ] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

### CODE REVIEW

**Comment by jkoenig134** [comment]
@Milena-Czierlinski as we are the only consumers we can keep this removed silently! :)

**Comment by Milena-Czierlinski** [comment]
@sebbi08 expressed his concern that the previous release introduced a breaking change for integrators.

**Comment by jkoenig134** [comment]
IMO as the API is unchanged and we don't know about any consumers of the js sdk than us we can ignore it.

**Comment by jkoenig134** [comment]
also I don't expect that someone is already using this functionality

**Comment by jkoenig134** [comment]
@sebbi08 as you requested this, any word from your side for or against this?

**Comment by sebbi08** [comment]
If we are sure that no one uses this, I am also fine with just removing it. Otherwise, this would be a breaking change.

**Pull request closed without merging**
