### PR TITLE
Refactoring/remove mustbeaccepted of requestitemgroup

### PR DESCRIPTION
**Pull request by britsta**
Can only be merged after https://github.com/nmshd/runtime/pull/183 is merged. (Merged now.)

# Readiness checklist

-   [x] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

### CODE REVIEW

**Comment by jkoenig134** [comment]
@britsta shouldn't this be first done in the runtime? 🤨

**Comment by britsta** [comment]
> @britsta shouldn't this be first done in the runtime? 🤨

Sure! Review already requested https://github.com/nmshd/runtime/pull/183 🐸 I just created this draft PR for myself so that I don't forget to change it in the Connector. :D

**Comment by jkoenig134** [comment]
Oooooh, sorry 😔 don't know Why I was notified

**Comment by britsta** [comment]
> Oooooh, sorry 😔 don't know Why I was notified

@jkoenig134 No problem, it may have been my fault 😂 Btw, am I authorized to delete remote branches? I accidentally created one that I would like to remove 😊

**Review by jkoenig134 — APPROVED** [review]

**Review by sebbi08 — APPROVED** [review]

**Review by jkoenig134 — APPROVED** [review]

**Pull request merged**
