### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sebbi08**
# Readiness checklist

-   [x] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.
-   [x] I self-reviewed the PR.

### CODE REVIEW

**Review by Milena-Czierlinski — APPROVED** [review]
Is dependabot already on vacation?

**Review by Magnus-Kuhn — COMMENTED** [review]
ncu on main also showed that eslint can be updated to 9.16.0, was omitting this a deliberate choice?

**Comment by sebbi08** [comment]
> ncu on main also showed that eslint can be updated to 9.16.0, was omitting this a deliberate choice?

yes typescript eslint is not 9.x ready

**Comment by sebbi08** [comment]
> Is dependabot already on vacation?

No but there was a current security issue in one of our dependencies

**Comment by jkoenig134** [comment]
> Is dependabot already on vacation?

LMAO

**Pull request merged**
